version: "3"
services:
  nginx:
    image: nginx:1.19.8-alpine
    labels:
      lets-proxy.domain: "docker-test.internal"
    networks:
      acmenet:
        ipv4_address: 10.40.50.12
  test:
    image: golang:${GO_VERSION:-1.18}
    working_dir: /go/src/github.com/rekby/lets-proxy2
    command: go test -covermode=count -coverprofile=coverage.out ${LETS_PROXY_TEST_OPTIONS:-} ./...
    environment:
      GOCACHE: "/go/src/github.com/rekby/lets-proxy2/.cache"
      GOFLAGS: "-mod=vendor"
      GO111MODULE: "on"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/go/src/github.com/rekby/lets-proxy2
    networks:
      acmenet:
        ipv4_address: 10.40.50.4
    depends_on:
       - nginx
networks:
  acmenet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.40.50.0/24