name: publish
on: push
jobs:
  publish:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        goVersion: ["1.10", "1.16"]
    env:
      GO_VERSION: ${{ matrix.goVersion }}
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.goVersion }}

      - name: checkout
        uses: actions/checkout@v2

      - name: build release binaries
        run: bash ./tests/build-release.sh
